### ISSUE TITLE
反馈：快速开始 PWA 工程

### ISSUE THREAD

**Issue by zaofeng** [searchfe/bpwa-tutorial-doc#16]
参照文档来，提示项目创建成功，但是是一个空项目
![20171214](https://user-images.githubusercontent.com/15383129/34000209-942dd9f4-e127-11e7-9d56-da2ae801176e.jpg)

**Comment by PengXing** [comment]
似乎从 github 上克隆项目的时候出现错误了，你访问 github 是否稳定？
