### ISSUE TITLE
反馈：sw-register-webpack-plugin 插件

### ISSUE THREAD

**Issue by mytxzz** [searchfe/bpwa-tutorial-doc#17]
sw-register.js文件不带hash？难道这个文件需要单独配置cdn header？

**Comment by zoumiaojiang** [comment]
你好，我们的设计就是需要让 `sw-register.js` 做为控制 service worker 安装或者更新等操作的入口，这个静态资源文件应该是完全不能够被缓存包括浏览器缓存，在离线情况下它也不会影响具体业务逻辑，如果使用 hash 的方式意味着编译的时候就需要编译进 appShell 页面，这样 sw-register.js 还是绕不开浏览器缓存。具体的可以看这篇文章：https://zhuanlan.zhihu.com/p/28161855 关于 「service worker 文件 no-cache 处理」

**Comment by mytxzz** [comment]
感谢回复，文章写的真不错，赞
