### ISSUE TITLE
反馈：启动lavas 调试服务器失败 lavas2

### ISSUE THREAD

**Issue by clevok** [searchfe/bpwa-tutorial-doc#19]
!['失败了'](http://mianjiba.com/image/error.png)
百度大大，不晓得为啥，我一直这样错误，(┬＿┬) ，尝试了好久，卸载重装，是因为我用了*`cnpm`*的原因吗，我这是2版本的，文档说跳过了选择模版，我发现我cnpm下过来依然要选择模版，`cnpm install lavas@lavas2 -g`，所以我在想是不是我cnpm有问题呀

**Comment by lceric** [comment]
刚更新了下lavas，跟这个一样，也是这个问题

**Comment by easonyq** [comment]
这是我们首页安装教程中的更新问题所致，可以参考 [这里](https://github.com/lavas-project/lavas/issues/26)

应该使用 `npm install lavas -g` 而非 `npm install lavas@lavas2 -g` 。

对于首页的显示问题我们深感抱歉= =!
