### ISSUE TITLE
反馈：开发一个页面

### ISSUE THREAD

**Issue by shengwong233** [searchfe/bpwa-tutorial-doc#2]
我通过局域网在手机上打开项目，显示了基础框架样式之后，内容不显示，手机是oneplus3，安卓版本7.1，系统版本oneplus A3000_16_170627，浏览器使用的系统自带，也使用了夸克浏览器v2.0.0.918，都出现了这个问题

**Comment by easonyq** [comment]
您好，能否麻烦提供一下具体描述，例如
1. 给个截图？
2. 是使用lavas init创建的项目吗？使用的是哪个模板呢？例如basic？
3. 使用什么命令起的项目？是npm run dev还是npm run build之后再使用什么服务器启动的呢？

谢谢啦~

**Comment by easonyq** [comment]
你好，我们在开发模式(npm run dev)中注入了一段代码，使用了es6的相关语法但是你的浏览器不支持因此产生了错误。目前已经修复。
