### ISSUE TITLE
反馈：v2/basic/install.md

### ISSUE THREAD

**Issue by yin2017168** [searchfe/bpwa-tutorial-doc#24]
![image](https://user-images.githubusercontent.com/26922373/35961527-ec205690-0ce8-11e8-9212-6ecb667824dc.png)

**Comment by PengXing** [comment]
看报错，是当前没有 git 命令，在这个命令行里运行一下 `git`，把输出结果贴出来一下看看

**Comment by yin2017168** [comment]
关键没玩过git,,如何入手，之前都玩svn



771825387@qq.com
 
发件人： PengXing
发送时间： 2018-02-08 16:13
收件人： lavas-project/lavas-tutorial
抄送： yin2017168; Author
主题： Re: [lavas-project/lavas-tutorial] 反馈：v2/basic/install.md (#24)
看报错，是当前没有 git 命令，在这个命令行里运行一下 git，把输出结果贴出来一下看看

**Comment by PengXing** [comment]
不需要你玩 git，你把 git 安装一下就行了
