### ISSUE TITLE
反馈：v2/advanced/core.md

### ISSUE THREAD

**Issue by yuu2lee4** [searchfe/bpwa-tutorial-doc#27]
index.html.tmpl  并没有这个文件

**Comment by PengXing** [comment]
ok，不好意思

这个文件拆分成 spa.html.tmpl 和 ssr.html.tmpl 了，但其实是一样的

我们去修改一下文档

**Comment by easonyq** [comment]
@yuu2lee4 我已经对文档进行了修改，多谢指正。
