### ISSUE TITLE
反馈：vue/webpack/vue-skeleton-webpack-plugin.md

### ISSUE THREAD

**Issue by xugc** [searchfe/bpwa-tutorial-doc#29]
TypeError: Cannot read property 'source' of undefined
    at E:\Visual Studio Code WorkSpace\my-pwa\node_modules\vue-skeleton-webpack-plugin\lib\ssr.js:75:74

**Comment by PengXing** [comment]
Duplicate of https://github.com/lavas-project/lavas/issues/160
