### ISSUE TITLE
反馈：开发一个页面

### ISSUE THREAD

**Issue by huanghuiquan** [searchfe/bpwa-tutorial-doc#3]
文档链接有不对，如截图

![image](https://user-images.githubusercontent.com/1880596/27899579-571fb4c2-625d-11e7-89f3-5930594420ce.png)

**Comment by PengXing** [comment]
已经修改，可以通过这个链接预览 https://lavas.baidu.com/guide/vue/doc/vue/01-foundation/03-how-to-add-a-page
