### ISSUE TITLE
反馈：v2/basic/init.md

### ISSUE THREAD

**Issue by diliburong** [searchfe/bpwa-tutorial-doc#30]
当我想生成嵌套路由，在照着 嵌套路由的lavas教程左后， `article`目录下有`_id` 和`create` 两个vue文件并且也在`article`目录外创建了`Article.vue`。但是当我访问`article/create`依旧跳转到`_id`目录下？

**Comment by easonyq** [comment]
你好。关于路由配置这块，如果文档描述的不够清楚，我后面还写了一个 ISSUE 描述了具体实践中一些常遇到的问题，你可以关注一下：[Lavas 的路由配置规则实践](https://github.com/lavas-project/lavas/issues/141)

具体到你的问题，既然你创建了和目录 `article` 同名的 `Article.vue` 文件，那就表示这里是一个 __嵌套路由__。因此在 `Article.vue` 里面就需要有 `<router-view>` 标签来容纳子路由内容，这个我不知道你实现了没有。

然后你描述中

> 但是当我访问 `article/create` 依旧跳转到 `_id` 目录下？

这个我不太理解，`_id` 不是一个 vue 文件么？怎么是目录呢？

希望你能提供更详细的问题描述，我们在这个 ISSUE 中继续讨论。

**Comment by diliburong** [comment]
你好，我`<router-view>` 这个之前我已经实现了，现在我想实现的路由是：
`/article /:id` 跳转到 article详情页面
`/article/create ` 跳转到创建页面
但当每次我访问`/article/create ` 时，识别到的依旧是`/article /:id`并跳转到`article` 详情页面

**Comment by easonyq** [comment]
我不清楚你是不是配置的有点问题，我刚才按照你的描述自己创建了一个项目，是正常的。我提供一下我的写法和配置，你比对一下是否有不同吧~~

## pages 目录结构
![image](https://user-images.githubusercontent.com/6800839/40460964-c19a7d60-5f3b-11e8-84dc-ef1766e52f1f.png)

忽略 `Appshell.vue`, `Error.vue` 和 `Index.vue`。这三个都是初始创建项目就有的。

## 具体页面内容

具体的页面 vue 为了方便起见只编写了 `<template>` 的部分。其他 `<script>` 和 `<style>` 都用最基本的或者不写，只为展示页面效果。

### Article.vue

嵌套路由的父页面，如下：

```html
<template>
    <div class="page-index">
        <h2>Article</h2>
        <router-view></router-view>
    </div>
</template>
```

### article/_id.vue

`/article/:id` 路由目标页面

```html
<template>
    <div class="page-index">
        <h2>Article/{{ $route.params.id }}</h2>
    </div>
</template>
```

### article/Create.vue

`/article/create` 路由目标页面

```html
<template>
    <div class="page-index">
        <h2>Article/create</h2>
    </div>
</template>
```

## 实际访问效果

1. 访问 `/article/1` 时：

![image](https://user-images.githubusercontent.com/6800839/40461149-8b26f58c-5f3c-11e8-9382-217bf18e99dd.png)

2. 访问 `/article/create` 时：

![image](https://user-images.githubusercontent.com/6800839/40461201-c31c5c52-5f3c-11e8-9ba6-742d6bf97745.png)
