### ISSUE TITLE
反馈：v2/basic/install.md

### ISSUE THREAD

**Issue by chunshand** [searchfe/bpwa-tutorial-doc#31]
Module build failed: Error: No parser and no file path given, couldn't infer a parser.
![image](https://user-images.githubusercontent.com/20159933/40595595-1ce8091a-6268-11e8-929e-9558318822d4.png)

**Comment by PengXing** [comment]
问题已收到，正在处理，谢谢

**Comment by easonyq** [comment]
@chunshan-pro 这是由于 Vuejs 依赖的一个类库 prettier 更新导致的问题，issue 在 [这里](https://github.com/vuejs/component-compiler-utils/issues/14)

我们会在之后更新类库以解决问题，感谢反馈。

**Comment by PengXing** [comment]
https://github.com/vuejs/component-compiler-utils/issues/14

就是这个错误，和 lavas 本身无关，不过我们也已经通过升级 `prettier` 修复了

1. 重新 init 一个 lavas 项目
2. 在项目根目录运行 `npm install prettier@1.12.1 --save`
