### ISSUE TITLE
反馈：快速开始 PWA 工程

### ISSUE THREAD

**Issue by boboox** [searchfe/bpwa-tutorial-doc#5]
init项目的时候就卡在
LAVAS INFO 欢迎使用 Lavas 解决方案
LAVAS INFO 新建一个 PWA 项目

...
这个位置了

**Comment by PengXing** [comment]
请问是什么操作系统，以及 node 和 npm 的版本呢，有助于我们排查问题 = =

**Comment by boboox** [comment]
mac 10.12 node v4.6.1 npm v3.10.9

**Comment by boboox** [comment]
是不是init的时候需要去拉你们那个lavas-template-vue-appshell这个项目模板?也可能是我们的网络问题 T_T

**Comment by PengXing** [comment]
嗯。。很有可能，难道是网络不太好，template 是从 git 上拉取的，现在命令行还没加上下载提示，体验还有待改进。

**Comment by zoumiaojiang** [comment]
已添加云端下载的提示，等发新版会更新的。
