### ISSUE TITLE
反馈：探索 PWA

### ISSUE THREAD

**Issue by zhangzhiqiang37** [searchfe/bpwa-tutorial-doc#9]
1、service worker的缓存也会占据存储空间，占用大小区别而已，严谨一点不能说不占用存储空间
2、SPA那一节第二段中 “从 Ajax 开始，越来越多的单页富应用 (SPA) 问世，并且在实现和体验上有着非常高效的解决方案” 这句话真真没看懂，完全不知道在说什么，从ajax（技术）说起，说到SPA（某类应用），然后又直接转到解决方案，三句话之间都不通的

**Comment by PengXing** [comment]
改了么。。

**Comment by zhangzhiqiang37** [comment]
没改，找原作者改把，不太清楚应该怎么改
